import { User, Condominium, ServiceProvider, Recommendation, ServiceCategory } from '../types';

// Usuários mock
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao@email.com',
    phone: '(11) 99999-9999',
    apartment: '101',
    building: 'Torre A',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Joao',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria@email.com',
    phone: '(11) 88888-8888',
    apartment: '202',
    building: 'Torre B',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    createdAt: new Date('2024-01-16'),
  },
  {
    id: '3',
    name: 'Carlos Oliveira',
    email: 'carlos@email.com',
    phone: '(11) 77777-7777',
    apartment: '303',
    building: 'Torre A',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    createdAt: new Date('2024-01-17'),
  },
  {
    id: '4',
    name: 'Ana Souza',
    email: 'ana@email.com',
    phone: '(11) 66666-6666',
    apartment: '404',
    building: 'Torre C',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    createdAt: new Date('2024-01-18'),
  },
];

// Condomínios mock
export const mockCondominiums: Condominium[] = [
  {
    id: '1',
    name: 'Residencial Primavera',
    address: 'Rua das Flores, 123',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01234-567',
    adminId: '1',
    createdAt: new Date('2024-01-01'),
    members: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[3]],
  },
  {
    id: '2',
    name: 'Condomínio Sol Nascente',
    address: 'Av. do Sol, 456',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zipCode: '23456-789',
    adminId: '2',
    createdAt: new Date('2024-01-02'),
    members: [mockUsers[1], mockUsers[2]],
  },
];

// Prestadores de serviço mock
export const mockProviders: ServiceProvider[] = [
  {
    id: '1',
    name: 'Limpeza Total',
    category: 'limpeza',
    description: 'Serviço de limpeza residencial e comercial com profissionais treinados',
    phone: '(11) 1111-1111',
    email: 'contato@limpezatotal.com',
    website: 'https://limpezatotal.com',
    address: 'Rua da Limpeza, 100',
    rating: 4.8,
    reviewCount: 120,
    recommendedBy: [mockUsers[0], mockUsers[1]],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-25'),
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400'],
  },
  {
    id: '2',
    name: 'Manutenção Rápida',
    category: 'manutencao',
    description: 'Serviços gerais de manutenção predial e residencial',
    phone: '(11) 2222-2222',
    email: 'manutencao@rapida.com',
    rating: 4.5,
    reviewCount: 85,
    recommendedBy: [mockUsers[2]],
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-26'),
    images: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400'],
  },
  {
    id: '3',
    name: 'Pintura & Acabamento',
    category: 'pintura',
    description: 'Pintura de paredes, tetos e acabamentos em geral',
    phone: '(11) 3333-3333',
    email: 'pintura@acabamento.com',
    rating: 4.9,
    reviewCount: 200,
    recommendedBy: [mockUsers[0], mockUsers[3]],
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-24'),
    images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400'],
  },
  {
    id: '4',
    name: 'Jardim Verde',
    category: 'jardinagem',
    description: 'Manutenção de jardins, poda de árvores e paisagismo',
    phone: '(11) 4444-4444',
    email: 'jardim@verde.com',
    rating: 4.7,
    reviewCount: 150,
    recommendedBy: [mockUsers[1], mockUsers[2], mockUsers[3]],
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-27'),
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
  },
  {
    id: '5',
    name: 'Elétrica Segura',
    category: 'eletrica',
    description: 'Instalações e manutenções elétricas residenciais',
    phone: '(11) 5555-5555',
    email: 'eletrica@segura.com',
    rating: 4.6,
    reviewCount: 95,
    recommendedBy: [mockUsers[0]],
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-28'),
    images: ['https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400'],
  },
  {
    id: '6',
    name: 'Hidráulica Prática',
    category: 'hidraulica',
    description: 'Serviços hidráulicos, vazamentos e instalações',
    phone: '(11) 6666-6666',
    email: 'hidraulica@pratica.com',
    rating: 4.4,
    reviewCount: 70,
    recommendedBy: [mockUsers[2]],
    createdAt: new Date('2024-01-24'),
    updatedAt: new Date('2024-01-29'),
    images: ['https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400'],
  },
];

// Recomendações mock
export const mockRecommendations: Recommendation[] = [
  {
    id: '1',
    providerId: '1',
    provider: mockProviders[0],
    userId: '1',
    user: mockUsers[0],
    condominiumId: '1',
    comment: 'Excelente serviço! Deixaram minha casa impecável. Super recomendo!',
    rating: 5,
    tags: ['limpeza', 'residencial', 'profissional'],
    createdAt: new Date('2024-01-25T10:00:00'),
    updatedAt: new Date('2024-01-25T10:00:00'),
  },
  {
    id: '2',
    providerId: '1',
    provider: mockProviders[0],
    userId: '2',
    user: mockUsers[1],
    condominiumId: '1',
    comment: 'Bom serviço, mas um pouco caro. Vale a pena pela qualidade.',
    rating: 4,
    tags: ['limpeza', 'qualidade'],
    createdAt: new Date('2024-01-24T14:30:00'),
    updatedAt: new Date('2024-01-24T14:30:00'),
  },
  {
    id: '3',
    providerId: '3',
    provider: mockProviders[2],
    userId: '3',
    user: mockUsers[2],
    condominiumId: '1',
    comment: 'Pintura perfeita! Fizeram um trabalho impecável no meu apartamento.',
    rating: 5,
    tags: ['pintura', 'acabamento', 'perfeito'],
    createdAt: new Date('2024-01-23T09:15:00'),
    updatedAt: new Date('2024-01-23T09:15:00'),
  },
  {
    id: '4',
    providerId: '4',
    provider: mockProviders[3],
    userId: '4',
    user: mockUsers[3],
    condominiumId: '1',
    comment: 'Jardineiro muito atencioso e competente. Meu jardim nunca esteve tão bonito!',
    rating: 5,
    tags: ['jardinagem', 'poda', 'paisagismo'],
    createdAt: new Date('2024-01-22T16:45:00'),
    updatedAt: new Date('2024-01-22T16:45:00'),
  },
  {
    id: '5',
    providerId: '2',
    provider: mockProviders[1],
    userId: '1',
    user: mockUsers[0],
    condominiumId: '1',
    comment: 'Resolveram o problema do meu chuveiro rapidamente. Ótimo atendimento.',
    rating: 5,
    tags: ['manutencao', 'chuveiro', 'rapido'],
    createdAt: new Date('2024-01-21T11:20:00'),
    updatedAt: new Date('2024-01-21T11:20:00'),
  },
  {
    id: '6',
    providerId: '5',
    provider: mockProviders[4],
    userId: '2',
    user: mockUsers[1],
    condominiumId: '1',
    comment: 'Eletricista muito competente. Fez a instalação das minhas lâmpadas LED.',
    rating: 4,
    tags: ['eletrica', 'instalacao', 'led'],
    createdAt: new Date('2024-01-20T15:10:00'),
    updatedAt: new Date('2024-01-20T15:10:00'),
  },
];

// Categorias de serviço
export const serviceCategories: { value: ServiceCategory; label: string; icon: string }[] = [
  { value: 'limpeza', label: 'Limpeza', icon: '🧹' },
  { value: 'manutencao', label: 'Manutenção', icon: '🔧' },
  { value: 'reforma', label: 'Reforma', icon: '🏗️' },
  { value: 'jardinagem', label: 'Jardinagem', icon: '🌿' },
  { value: 'pintura', label: 'Pintura', icon: '🎨' },
  { value: 'eletrica', label: 'Elétrica', icon: '⚡' },
  { value: 'hidraulica', label: 'Hidráulica', icon: '💧' },
  { value: 'seguranca', label: 'Segurança', icon: '🔒' },
  { value: 'entrega', label: 'Entrega', icon: '📦' },
  { value: 'outros', label: 'Outros', icon: '📋' },
];

// Dados de exemplo para o usuário atual
export const currentUser: User = mockUsers[0];
export const currentCondominium: Condominium = mockCondominiums[0];
